apiVersion: v1
kind: Service
metadata:
  name: housekeeping-service
  namespace: hotel
spec:
  selector:
    app: housekeeping-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP