apiVersion: v1
kind: ConfigMap
metadata:
  name: hotel-config
  namespace: hotel
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://hotel-postgres:5432/hoteldb
  SPRING_RABBITMQ_HOST: hotel-rabbitmq
  SPRING_JPA_HIBERNATE_DDL_AUTO: update